# see docs: https://docs.travis-ci.com/user/languages/ruby/
language: ruby
rvm:
  - 2.2
  - jruby
  - 2.0.0-p247
bundler_args: --without production
install:
  - bundle install --jobs=3 --retry=3
  - wget 'https://github.com/googlecodelabs/tools/releases/download/v1.1.0/claat-linux-amd64' --output-document=claat
# Ver https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
